// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ExportBackup():Promise<string>;

export function ImportBackup(arg1:string,arg2:string):Promise<string>;

export function ResetLibrary():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
