// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportBackup() {
  return window['go']['handlers']['BackupHandler']['ExportBackup']();
}

export function ImportBackup(arg1, arg2) {
  return window['go']['handlers']['BackupHandler']['ImportBackup'](arg1, arg2);
}

export function ResetLibrary() {
  return window['go']['handlers']['BackupHandler']['ResetLibrary']();
}

export function Startup(arg1) {
  return window['go']['handlers']['BackupHandler']['Startup'](arg1);
}
