// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicenseKey(arg1) {
  return window['go']['handlers']['LicenseHandler']['ActivateLicenseKey'](arg1);
}

export function AdminExtendUserLicense(arg1, arg2) {
  return window['go']['handlers']['LicenseHandler']['AdminExtendUserLicense'](arg1, arg2);
}

export function AdminGenerateKey(arg1, arg2) {
  return window['go']['handlers']['LicenseHandler']['AdminGenerateKey'](arg1, arg2);
}

export function AdminGetAllUsers() {
  return window['go']['handlers']['LicenseHandler']['AdminGetAllUsers']();
}

export function AdminRevokeUserLicense(arg1) {
  return window['go']['handlers']['LicenseHandler']['AdminRevokeUserLicense'](arg1);
}

export function GetLicenseStatus() {
  return window['go']['handlers']['LicenseHandler']['GetLicenseStatus']();
}

export function LoginAccount(arg1, arg2) {
  return window['go']['handlers']['LicenseHandler']['LoginAccount'](arg1, arg2);
}

export function LoginWithGoogle() {
  return window['go']['handlers']['LicenseHandler']['LoginWithGoogle']();
}

export function Logout() {
  return window['go']['handlers']['LicenseHandler']['Logout']();
}

export function RegisterAccount(arg1, arg2, arg3) {
  return window['go']['handlers']['LicenseHandler']['RegisterAccount'](arg1, arg2, arg3);
}
