// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ActivateLicenseKey(arg1:string):Promise<domain.UserProfile>;

export function AdminExtendUserLicense(arg1:string,arg2:number):Promise<string>;

export function AdminGenerateKey(arg1:string,arg2:number):Promise<string>;

export function AdminGetAllUsers():Promise<Array<domain.UserProfile>>;

export function AdminRevokeUserLicense(arg1:string):Promise<string>;

export function GetLicenseStatus():Promise<domain.UserProfile>;

export function LoginAccount(arg1:string,arg2:string):Promise<domain.UserProfile>;

export function LoginWithGoogle():Promise<domain.UserProfile>;

export function Logout():Promise<string>;

export function RegisterAccount(arg1:string,arg2:string,arg3:string):Promise<domain.UserProfile>;
