// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ExportPrintSheet(arg1:domain.PrintRequest):Promise<domain.PrintResult>;
