// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPrintSheet(arg1) {
  return window['go']['handlers']['PrintHandler']['ExportPrintSheet'](arg1);
}
