// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProject(arg1) {
  return window['go']['handlers']['ProjectHandler']['DeleteProject'](arg1);
}

export function GetAllProjects() {
  return window['go']['handlers']['ProjectHandler']['GetAllProjects']();
}

export function GetProject(arg1) {
  return window['go']['handlers']['ProjectHandler']['GetProject'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['handlers']['ProjectHandler']['SaveProject'](arg1);
}
