// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function DeleteProject(arg1:string):Promise<string>;

export function GetAllProjects():Promise<Array<domain.Project>>;

export function GetProject(arg1:string):Promise<domain.Project>;

export function SaveProject(arg1:domain.Project):Promise<string>;
