import type React from "react";
import {
  ContactCard20Filled,
  DocumentPerson20Filled,
  Airplane20Filled,
  Image20Filled,
  Grid20Filled,
} from "@fluentui/react-icons";
import type { PhotoTemplate, TemplateCategory } from "./types";

export const PHOTO_TEMPLATES: PhotoTemplate[] = [
  // === الوثائق الرسمية العراقية ===
  {
    id: "iq-national-id",
    name: "البطاقة الوطنية الموحدة العراقية · 35×45 ملم",
    category: "id",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء صلبة، الرأس يشغل 70-80%",
    icon: ContactCard20Filled,
    notes: "المواصفات الرسمية لمديرية الأحوال المدنية والجوازات والإقامة العراقية",
  },
  {
    id: "iq-passport",
    name: "جواز السفر العراقي / الإلكتروني · 35×45 ملم",
    category: "passport",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء صلبة، الرأس يشغل 70-80%",
    icon: DocumentPerson20Filled,
    notes: "المقاس الرسمي لجواز السفر العراقي المقروء آلياً والبيومتري الجديد",
  },
  {
    id: "iq-civil-id",
    name: "هوية الأحوال / الجنسية العراقية · 32×40 ملم",
    category: "id",
    width: 378,
    height: 472,
    widthMM: 32,
    heightMM: 40,
    dpi: 300,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: ContactCard20Filled,
    notes: "المقاس التقليدي لهوية الأحوال المدنية وشهادة الجنسية العراقية",
  },
  {
    id: "iq-general-id",
    name: "المعاملات العراقية / هوية النقابة · 40×60 ملم",
    category: "id",
    width: 472,
    height: 709,
    widthMM: 40,
    heightMM: 60,
    dpi: 300,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: ContactCard20Filled,
    notes: "مقاس صورة المعاملات الرسمية العامة، والجامعات، ونقابات المهن العراقية",
  },
  {
    id: "iq-pension",
    name: "معاملات المتقاعدين والدوائر · 30×40 ملم",
    category: "id",
    width: 354,
    height: 472,
    widthMM: 30,
    heightMM: 40,
    dpi: 300,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: ContactCard20Filled,
    notes: "المقاس المستخدم لهوية المتقاعدين وبطاقات الرعاية الاجتماعية والدوائر العامة في العراق",
  },

  // === بطاقة الهوية المدنية ===
  {
    id: "id-30x40",
    name: "هوية مدنية · 30×40 ملم",
    category: "id",
    width: 354,
    height: 472,
    widthMM: 30,
    heightMM: 40,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: ContactCard20Filled,
    notes: "المقاس القياسي للبطاقة الوطنية الموحدة",
  },
  {
    id: "id-35x45",
    name: "هوية مدنية · 35×45 ملم",
    category: "id",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: ContactCard20Filled,
    notes: "المقاس القياسي البديل للهوية",
  },
  {
    id: "id-33x48",
    name: "هوية مدنية · 33×48 ملم",
    category: "id",
    width: 390,
    height: 567,
    widthMM: 33,
    heightMM: 48,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: ContactCard20Filled,
  },

  // === جواز السفر ===
  {
    id: "passport-35x45",
    name: "جواز سفر · 35×45 ملم",
    category: "passport",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: DocumentPerson20Filled,
    notes: "المعيار الدولي ICAO 9303",
  },
  {
    id: "passport-33x48",
    name: "جواز سفر · 33×48 ملم",
    category: "passport",
    width: 390,
    height: 567,
    widthMM: 33,
    heightMM: 48,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: DocumentPerson20Filled,
  },
  {
    id: "passport-40x60",
    name: "جواز سفر · 40×60 ملم",
    category: "passport",
    width: 472,
    height: 709,
    widthMM: 40,
    heightMM: 60,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: DocumentPerson20Filled,
  },
  {
    id: "passport-50x50",
    name: "جواز سفر · 50×50 ملم",
    category: "passport",
    width: 591,
    height: 591,
    widthMM: 50,
    heightMM: 50,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: DocumentPerson20Filled,
    notes: "المعيار الأمريكي وبعض الدول الأخرى",
  },
  {
    id: "passport-50x70",
    name: "جواز سفر · 50×70 ملم",
    category: "passport",
    width: 591,
    height: 827,
    widthMM: 50,
    heightMM: 70,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: DocumentPerson20Filled,
    notes: "المعيار الكندي للجوازات",
  },
];

export const TEMPLATES_BY_CATEGORY = (
  (["id", "passport", "visa", "personal", "collage"] as TemplateCategory[]).reduce(
    (acc, cat) => {
      acc[cat] = PHOTO_TEMPLATES.filter((t) => t.category === cat);
      return acc;
    },
    {} as Record<TemplateCategory, PhotoTemplate[]>
  )
) as Record<TemplateCategory, PhotoTemplate[]>;

export const CATEGORY_LABELS: Record<TemplateCategory, string> = {
  id: "بطاقة الهوية",
  passport: "جواز السفر",
  visa: "التأشيرة",
  personal: "صور شخصية",
  collage: "كولاج",
};

export const CATEGORY_ICONS: Record<TemplateCategory, React.ComponentType<any>> = {
  id: ContactCard20Filled,
  passport: DocumentPerson20Filled,
  visa: Airplane20Filled,
  personal: Image20Filled,
  collage: Grid20Filled,
};
