import type React from "react";
import {
  IdCardIcon,
  PassportIcon,
  Airplane01Icon,
  Image02Icon,
  Grid02Icon,
} from "@hugeicons/core-free-icons";
import type { PhotoTemplate, TemplateCategory } from "./types";

export const PHOTO_TEMPLATES: PhotoTemplate[] = [
  // ==========================================
  // 🇮🇶 1. الوثائق الرسمية العراقية
  // ==========================================
  {
    id: "iq-national-id",
    name: "البطاقة الوطنية الموحدة العراقية · 35×45 ملم",
    category: "id",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء صلبة، الرأس يشغل 70-80%",
    icon: IdCardIcon,
    notes: "المواصفات الرسمية لمديرية الأحوال المدنية والجوازات والإقامة العراقية",
  },
  {
    id: "iq-passport",
    name: "جواز السفر العراقي / الإلكتروني · 35×45 ملم",
    category: "passport",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء صلبة، الرأس يشغل 70-80%",
    icon: PassportIcon,
    notes: "المقاس الرسمي لجواز السفر العراقي المقروء آلياً والبيومتري الجديد",
  },
  {
    id: "iq-civil-id",
    name: "هوية الأحوال / الجنسية العراقية · 32×40 ملم",
    category: "id",
    width: 378,
    height: 472,
    widthMM: 32,
    heightMM: 40,
    dpi: 300,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: IdCardIcon,
    notes: "المقاس التقليدي لهوية الأحوال المدنية وشهادة الجنسية العراقية",
  },
  {
    id: "iq-general-id",
    name: "المعاملات العراقية / هوية النقابة · 40×60 ملم",
    category: "id",
    width: 472,
    height: 709,
    widthMM: 40,
    heightMM: 60,
    dpi: 300,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: IdCardIcon,
    notes: "مقاس صورة المعاملات الرسمية العامة، والجامعات، ونقابات المهن العراقية",
  },
  {
    id: "iq-pension",
    name: "معاملات المتقاعدين والدوائر · 30×40 ملم",
    category: "id",
    width: 354,
    height: 472,
    widthMM: 30,
    heightMM: 40,
    dpi: 300,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: IdCardIcon,
    notes: "المقاس المستخدم لهوية المتقاعدين وبطاقات الرعاية الاجتماعية والدوائر العامة في العراق",
  },

  // ==========================================
  // 🌍 2. المعايير الدولية وجوازات السفر الكبرى
  // ==========================================
  {
    id: "icao-standard",
    name: "المعيار الدولي البيومتري (ICAO 9303) · 35×45 ملم",
    category: "passport",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء أو رمادية موحدة، الرأس 32-36 ملم (70-80%)",
    icon: PassportIcon,
    notes: "المعيار العالمي الرسمي المعتمد من منظمة الطيران المدني الدولي (ICAO Doc 9303)",
  },
  {
    id: "schengen-visa",
    name: "تأشيرة شنغن الأوروبية (Schengen Visa) · 35×45 ملم",
    category: "visa",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء أو رمادية فاتحة، الرأس 32-36 ملم",
    icon: Airplane01Icon,
    notes: "المواصفات الرسمية الموحدة لسفارات الاتحاد الأوروبي (ألمانيا، فرنسا، إيطاليا، إسبانيا، هولندا...)",
  },
  {
    id: "us-passport-visa",
    name: "جواز وفيزا أمريكا / اللوتري (US Visa/DS-160) · 51×51 ملم",
    category: "passport",
    width: 602,
    height: 602,
    widthMM: 51,
    heightMM: 51,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 69,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء ناصعة (2×2 إنش)، الرأس بين 25-35 ملم (50-69%)",
    icon: PassportIcon,
    notes: "المعيار الأمريكي الرسمي للجوازات والفيزا (DS-160) والجرين كارد واللوتري (USCIS)",
  },
  {
    id: "uk-passport",
    name: "جواز السفر والتأشيرة البريطانية (UK Passport) · 35×45 ملم",
    category: "passport",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 65,
    headHeightMax: 75,
    background: "#F1F5F9",
    backgroundHint: "خلفية رمادية فاتحة أو كريمية، الرأس بين 29-34 ملم",
    icon: PassportIcon,
    notes: "المواصفات المعتمدة لهيئة الجوازات البريطانية (HM Passport Office)",
  },
  {
    id: "canada-passport",
    name: "جواز السفر والتأشيرة الكندية (Canada Passport) · 50×70 ملم",
    category: "passport",
    width: 591,
    height: 827,
    widthMM: 50,
    heightMM: 70,
    dpi: 300,
    headHeightMin: 45,
    headHeightMax: 51,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء ناصعة بدون ظلال، الرأس بين 31-36 ملم",
    icon: PassportIcon,
    notes: "المعيار الكندي الصارم لجوازات السفر والإقامة الدائمة (IRCC Canada)",
  },
  {
    id: "turkey-residence",
    name: "الإقامة والجواز التركي (İkamet / Turkey) · 50×60 ملم",
    category: "id",
    width: 591,
    height: 709,
    widthMM: 50,
    heightMM: 60,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء بيومترية (5×6 سم)، الرأس 32-36 ملم",
    icon: IdCardIcon,
    notes: "المقاس البيومتري الرسمي المعتمد لإدارة الهجرة والجوازات التركية (Göç İdaresi)",
  },
  {
    id: "saudi-passport",
    name: "الجواز السعودي والإقامة والعمرة · 40×60 ملم",
    category: "passport",
    width: 472,
    height: 709,
    widthMM: 40,
    heightMM: 60,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء، الوجه واضح بدون نظارات",
    icon: PassportIcon,
    notes: "المواصفات المعتمدة للجواز السعودي وبطاقة الهوية الوطنية وتأشيرات العمرة والحج والإقامة",
  },
  {
    id: "saudi-evisa",
    name: "التأشيرة السياحية السعودية (Saudi E-Visa) · 35×45 ملم",
    category: "visa",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: Airplane01Icon,
    notes: "مقاس التأشيرة السياحية السعودية الإلكترونية ومنصة التأشيرات الموحدة (KSA Visa)",
  },
  {
    id: "uae-id-visa",
    name: "الهوية الإماراتية والتأشيرة (Emirates ID) · 35×45 ملم",
    category: "id",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء، الرأس يشغل 70-80%",
    icon: IdCardIcon,
    notes: "المواصفات الرسمية للهيئة الاتحادية للهوية والجنسية والجمارك الإماراتية (ICP)",
  },
  {
    id: "egypt-passport",
    name: "جواز السفر المصري وبطاقة الرقم القومي · 40×60 ملم",
    category: "passport",
    width: 472,
    height: 709,
    widthMM: 40,
    heightMM: 60,
    dpi: 300,
    headHeightMin: 60,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء ناصعة بدون ظلال",
    icon: PassportIcon,
    notes: "المقاس القياسي المعتمد لمصلحة الجوازات والهجرة والجنسية وقطاع الأحوال المدنية بمصر",
  },
  {
    id: "india-passport",
    name: "جواز السفر الهندي وتأشيرة OCI · 51×51 ملم",
    category: "passport",
    width: 602,
    height: 602,
    widthMM: 51,
    heightMM: 51,
    dpi: 300,
    headHeightMin: 60,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء صلبة (2×2 إنش)",
    icon: PassportIcon,
    notes: "المعيار المعتمد لسفارات الهند وتأشيرات OCI وجواز السفر الهندي",
  },
  {
    id: "china-passport",
    name: "جواز السفر والتأشيرة الصينية (China Visa) · 33×48 ملم",
    category: "passport",
    width: 390,
    height: 567,
    widthMM: 33,
    heightMM: 48,
    dpi: 300,
    headHeightMin: 60,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء، الرأس 28-33 ملم وعرض الوجه 15-22 ملم",
    icon: PassportIcon,
    notes: "المعيار الدقيق المعتمد لسفارات وقنصليات جمهورية الصين الشعبية",
  },
  {
    id: "australia-passport",
    name: "جواز السفر الأسترالي (Australia Passport) · 35×45 ملم",
    category: "passport",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء أو رمادية فاتحة، الرأس 32-36 ملم",
    icon: PassportIcon,
    notes: "المواصفات المعتمدة لمكتب الجوازات الأسترالي (Australian Passport Office)",
  },
  {
    id: "russia-passport",
    name: "جواز السفر والتأشيرة الروسية (Russian Passport) · 35×45 ملم",
    category: "passport",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء خالية من الظلال",
    icon: PassportIcon,
    notes: "المواصفات الرسمية المعتمدة للجواز الروسي الداخلي والخارجي",
  },
  {
    id: "japan-passport",
    name: "جواز السفر الياباني (Japan Passport) · 35×45 ملم",
    category: "passport",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 70,
    headHeightMax: 80,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء سادة، الرأس 32-36 ملم",
    icon: PassportIcon,
    notes: "المعايير المعتمدة لوزارة الخارجية اليابانية لتأشيرات وجوازات السفر",
  },

  // ==========================================
  // 📐 3. مقاسات الهويات والتأشيرات العامة
  // ==========================================
  {
    id: "id-30x40",
    name: "هوية عامة · 30×40 ملم",
    category: "id",
    width: 354,
    height: 472,
    widthMM: 30,
    heightMM: 40,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: IdCardIcon,
    notes: "المقاس القياسي للبطاقات والهويات المدنية المصغرة",
  },
  {
    id: "id-35x45",
    name: "هوية عامة · 35×45 ملم",
    category: "id",
    width: 413,
    height: 531,
    widthMM: 35,
    heightMM: 45,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: IdCardIcon,
    notes: "المقاس القياسي البديل للهويات والبطاقات الشخصية",
  },
  {
    id: "id-33x48",
    name: "هوية عامة · 33×48 ملم",
    category: "id",
    width: 390,
    height: 567,
    widthMM: 33,
    heightMM: 48,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: IdCardIcon,
  },
  {
    id: "id-40x60",
    name: "هوية ومعاملات · 40×60 ملم",
    category: "id",
    width: 472,
    height: 709,
    widthMM: 40,
    heightMM: 60,
    dpi: 300,
    headHeightMin: 50,
    headHeightMax: 70,
    background: "#FFFFFF",
    backgroundHint: "خلفية بيضاء",
    icon: IdCardIcon,
  },
];

export const TEMPLATES_BY_CATEGORY = (
  (["passport", "visa", "id", "personal", "collage"] as TemplateCategory[]).reduce(
    (acc, cat) => {
      acc[cat] = PHOTO_TEMPLATES.filter((t) => t.category === cat);
      return acc;
    },
    {} as Record<TemplateCategory, PhotoTemplate[]>
  )
) as Record<TemplateCategory, PhotoTemplate[]>;

export const CATEGORY_LABELS: Record<TemplateCategory, string> = {
  passport: "جوازات السفر",
  visa: "التأشيرات والفيزا",
  id: "بطاقات الهوية",
  personal: "صور شخصية",
  collage: "كولاج",
};

export const CATEGORY_ICONS: Record<TemplateCategory, any> = {
  passport: PassportIcon,
  visa: Airplane01Icon,
  id: IdCardIcon,
  personal: Image02Icon,
  collage: Grid02Icon,
};
