// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAutoSave():Promise<void>;

export function LoadAutoSave():Promise<string>;

export function OpenFile():Promise<string>;

export function SaveAutoSave(arg1:string):Promise<void>;

export function SaveFile(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
