// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyMaskToImage(arg1, arg2) {
  return window['go']['main']['App']['ApplyMaskToImage'](arg1, arg2);
}

export function ClearAutoSave() {
  return window['go']['main']['App']['ClearAutoSave']();
}

export function LoadAutoSave() {
  return window['go']['main']['App']['LoadAutoSave']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveAutoSave(arg1) {
  return window['go']['main']['App']['SaveAutoSave'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveFileDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2, arg3, arg4);
}

export function SaveImageFromBase64(arg1) {
  return window['go']['main']['App']['SaveImageFromBase64'](arg1);
}
