import { z } from "zod";

export const CanvasElementSchema = z.object({
  id: z.string(),
  type: z.enum(["image", "text", "shape"]),
  x: z.number(),
  y: z.number(),
  width: z.number(),
  height: z.number(),
  rotation: z.number(),
  opacity: z.number(),
  zIndex: z.number(),
  locked: z.boolean().optional(),
  visible: z.boolean().optional(),
  
  imageSrc: z.string().optional(),
  originalImageSrc: z.string().optional(),
  filter: z.string().optional(),
  brightness: z.number().optional(),
  contrast: z.number().optional(),
  saturation: z.number().optional(),
  blur: z.number().optional(),
  // خلفية عنصر الصورة (تُستخدم خلف الصور الشفافة) — كانت تُسقط سابقاً عند الحفظ (إصلاح Bug#3)
  bgColor: z.string().optional(),
  
  text: z.string().optional(),
  fontSize: z.number().optional(),
  fontWeight: z.number().optional(),
  color: z.string().optional(),
  fontFamily: z.string().optional(),
  textAlign: z.enum(["right", "center", "left"]).optional(),
  textBgColor: z.string().optional(),
  textBgRadius: z.number().optional(),
  textBgPadding: z.number().optional(),
  textBgPaddingX: z.number().optional(),
  textBgPaddingY: z.number().optional(),
  textBgBorderColor: z.string().optional(),
  textBgBorderWidth: z.number().optional(),
  lineHeight: z.number().optional(),
  letterSpacing: z.number().optional(),
  wordSpacing: z.number().optional(),
  fontStyle: z.enum(["normal", "italic"]).optional(),
  textDecoration: z.enum(["none", "underline", "line-through"]).optional(),
  textTransform: z.enum(["none", "uppercase", "lowercase", "capitalize"]).optional(),
  wrap: z.enum(["word", "char", "none"]).optional(),
  shadowGlow: z.boolean().optional(),
  curve: z.number().optional(),
  curveRadius: z.number().optional(),
  curveDirection: z.enum(["up", "down"]).optional(),
  arabicNumerals: z.boolean().optional(),
  
  shape: z.enum(["rect", "ellipse", "line", "star", "path"]).optional(),
  fill: z.string().optional(),
  stroke: z.string().optional(),
  strokeWidth: z.number().optional(),
  radius: z.number().optional(),

  // gradient properties
  fillType: z.enum(["solid", "linear", "radial"]).optional(),
  fillLinearGradientStartPoint: z.object({ x: z.number(), y: z.number() }).optional(),
  fillLinearGradientEndPoint: z.object({ x: z.number(), y: z.number() }).optional(),
  fillLinearGradientColorStops: z.array(z.union([z.number(), z.string()])).optional(),
  fillRadialGradientStartPoint: z.object({ x: z.number(), y: z.number() }).optional(),
  fillRadialGradientStartRadius: z.number().optional(),
  fillRadialGradientEndPoint: z.object({ x: z.number(), y: z.number() }).optional(),
  fillRadialGradientEndRadius: z.number().optional(),
  fillRadialGradientColorStops: z.array(z.union([z.number(), z.string()])).optional(),
  
  // خصائص متقدمة
  shadowColor: z.string().optional(),
  shadowBlur: z.number().optional(),
  shadowOffsetX: z.number().optional(),
  shadowOffsetY: z.number().optional(),
  shadowOpacity: z.number().optional(),
  cornerRadius: z.number().optional(),
  globalCompositeOperation: z.string().optional(),
  flipX: z.boolean().optional(),
  flipY: z.boolean().optional(),
  svgPath: z.string().optional(),
  groupId: z.string().optional(),
});

export const CanvasSlotSchema = z.object({
  id: z.string(),
  cellIndex: z.number(),
  x: z.number(),
  y: z.number(),
  w: z.number(),
  h: z.number(),
  presetType: z.string().optional(),
  label: z.string().optional(),
  imageSrc: z.string().optional(),
  // كانت تُسقط سابقاً عند الحفظ/التحميل فيتعطل "استعادة الأصل" ويختفي لون الخلية (إصلاح Bug#3)
  originalImageSrc: z.string().optional(),
  bgColor: z.string().optional(),
  filter: z.string().optional(),
  brightness: z.number().optional(),
  contrast: z.number().optional(),
  saturation: z.number().optional(),
  zoom: z.number().optional(),
  dragX: z.number().optional(),
  dragY: z.number().optional(),
  flipX: z.boolean().optional(),
  flipY: z.boolean().optional(),
  rotation: z.number().optional(),
});

export const PrintSettingsSchema = z.object({
  paperId: z.string(),
  paperWidthMM: z.number(),
  paperHeightMM: z.number(),
  marginMM: z.number(),
  gapMM: z.number().optional(),
  dpi: z.number(),
  copiesPerSheet: z.number(),
  showCutLines: z.boolean(),
  showEndCutLine: z.boolean().optional(),
  orientation: z.enum(["portrait", "landscape"]),
  fitToPage: z.boolean().optional(),
  repeatMode: z.enum(["all", "row", "column"]).optional(),
});

export const PhotoTemplateSchema = z.object({
  id: z.string(),
  name: z.string(),
  category: z.enum(["id", "passport", "visa", "personal", "collage"]),
  width: z.number(),
  height: z.number(),
  widthMM: z.number(),
  heightMM: z.number(),
  dpi: z.number(),
  headHeightMin: z.number().optional(),
  headHeightMax: z.number().optional(),
  background: z.string(),
  backgroundHint: z.string(),
  notes: z.string().optional(),
});

export const CollageTemplateSchema = z.object({
  id: z.string(),
  name: z.string(),
  slots: z.number(),
  cells: z.array(z.object({
    x: z.number(),
    y: z.number(),
    w: z.number(),
    h: z.number(),
    presetType: z.string().optional(),
    label: z.string().optional(),
    rotation: z.number().optional(),
  })),
  physicalLayout: z.object({
    type: z.string(),
    rows: z.number(),
    cols: z.number(),
    align: z
      .enum([
        "center",
        "top-left",
        "top-center",
        "top-right",
        "center-left",
        "center-right",
        "bottom-left",
        "bottom-center",
        "bottom-right",
      ])
      .optional(),
  }).optional(),
});

export const ProjectSchema = z.object({
  mode: z.enum(["single", "collage"]).default("single"),
  canvasWidth: z.number().default(413),
  canvasHeight: z.number().default(531),
  backgroundColor: z.string().default("#FFFFFF"),
  elements: z.array(CanvasElementSchema).default([]),
  slots: z.array(CanvasSlotSchema).default([]),
  template: PhotoTemplateSchema.nullable().default(null),
  collageTemplate: CollageTemplateSchema.nullable().default(null),
  printSettings: PrintSettingsSchema.optional(),
  
  // إعدادات شبكة الإرشاد
  showGrid: z.boolean().optional().default(false),
  gridSize: z.number().optional().default(50),
  gridColor: z.string().optional().default("#000000"),
  gridOpacity: z.number().optional().default(0.15),
  gridSubdivisions: z.number().optional().default(5),
  gridType: z.enum(["lines", "dots"]).optional().default("lines"),
  snapToGrid: z.boolean().optional().default(false),
  
  // إعدادات أعمدة التخطيط
  showColumns: z.boolean().optional().default(false),
  columnsCount: z.number().optional().default(12),
  columnsColor: z.string().optional().default("rgba(239, 68, 68, 0.08)"),
  columnsMargin: z.number().optional().default(20),
  columnsGutter: z.number().optional().default(12),
  
  // تخصيصات الكولاج
  collageGap: z.number().optional().default(0),
  collageMargin: z.number().optional().default(0),
  collageRadius: z.number().optional().default(0),
  collageShowCutLines: z.boolean().optional().default(false),
  collageShowEndCutLine: z.boolean().optional(),
  collageStrokeWidth: z.number().optional().default(0),
  collageStrokeColor: z.string().optional().default("#000000"),
  embeddedAssets: z.record(z.string(), z.string()).optional(),
});

export type ProjectData = z.infer<typeof ProjectSchema>;
